### ISSUE TITLE
Doors always say opening even when force closing app.  

### ISSUE THREAD

**Issue by TTVert** [brbeaird/SmartThings-MyQ-Edge#28]
Doors open but I cannot close them while the status is "opening".  
![image](https://user-images.githubusercontent.com/24374538/230796173-931b2dfb-ce70-4aa0-9b46-0931130fc1ff.png)

**Comment by mjb4450** [comment]
I have had the same issue since I installed edge drivers many months ago., my automations work but the icon does not work and says "Closing" constantly.   I thought I would update the driver from 2022-11-05T18:33:17.310536673 (MyQ ConnectorBETA) to a newer one listed on the change driver screen: MyQ Connector (2023-02-25T22:44:57:160872452 and it broke the communications completely so I had to go back to the original beta version and edit all of my automations as the garage door had to be re-added.

If there is a correct way to upgrade the driver I would love to know what I did wrong.. for now I want my automations to work more than the buttons in the app.

If it helps I could never get the docker stuff to work so I am simply running the windows executable and it works fine as long as it is running.   In the executable screen if I click the button in the app it does say "close" so the button does do something but never updates that it is closed or open..

thank you

**Comment by brbeaird** [comment]
The 2023-02-25 version of MyQ Connector is the latest one, so you're good there. Definitely don't bother with the BETA one.

I think the main issue is the SmartThings iOS app. Mine generally shows the status correctly, but I've noticed times when it's just totally off. If I want to see the status, I'll usually open up ActionTiles.
